### ISSUE TITLE
Shipping from different city

### ISSUE THREAD

**Issue by mauroagr** [nordweg/bearpost#73]
In my operation, we shipping from City A, and from City B. Then i need two different origin address using correios.
I dont know if have this in roadmap.
Thanks

**Comment by igorgaelzer** [comment]
We already accept different Accounts inside Bearpost. So you can have different addresses and Correios/Azul/Jadlog credentials for each account.

**Comment by mauroagr** [comment]
Understand, but i have different origin address using same credential. I think can add two accounts with same credential.

**Comment by igorgaelzer** [comment]
Yes, you can have different shipping accounts with the same credentials
