### ISSUE TITLE
Option to manually add history to shipment 

### ISSUE THREAD

**Issue by LucasKuhn** [nordweg/bearpost#78]
<img width="1657" alt="Bearpost" src="https://user-images.githubusercontent.com/26127185/67396666-5ad36a80-f57e-11e9-812a-39eb39e6eab4.png">

**Comment by LucasKuhn** [comment]
Talking with users we got the feedback that the History field already has a lot of information and adding things in the middle would be hard to read and hard to find. 

Currently working on adding Notes to Shipments, on a separate portion: 
<img width="1666" alt="Bearpost" src="https://user-images.githubusercontent.com/26127185/72436914-559e4a00-3780-11ea-8065-b2df1563847c.png">

**Comment by igorgaelzer** [comment]
@LucasKuhn awesome! I love the UI and that you added a picture to the thread 🙌
